Repository cloudera-labs/cloudera-deploy, pull requests merged in 2023-11, with the labels that each got.

#129 Update quickstart.sh to pin cldr-runner and cloudera-deploy
  quickstart.sh
Labels: bug

#131 Update README for guidance on checking credentials
  README.md
Labels: documentation

#132 Update README for minimum Python version
  README.md
Labels: documentation

#130 Add GCP datalake example
  public-cloud/gcp/datalake/.gitignore
  public-cloud/gcp/datalake/README.md
  public-cloud/gcp/datalake/ansible-navigator.yml
  public-cloud/gcp/datalake/definition.yml
  public-cloud/gcp/datalake/inventory.ini
  public-cloud/gcp/datalake/main.yml
  public-cloud/gcp/datalake/teardown.yml
Labels: enhancement
