Repository cloudera-labs/cloudera-deploy, pull requests merged in 2023-12, with the labels that each got.

#136 Create CDP Private Cloud Base on AWS IaaS definition
  private-cloud/base/aws-iaas/.gitignore
  private-cloud/base/aws-iaas/README.md
  private-cloud/base/aws-iaas/ansible-navigator.yml
  private-cloud/base/aws-iaas/base_postfix.yml
  private-cloud/base/aws-iaas/base_setup.yml
  private-cloud/base/aws-iaas/cluster.yml
  private-cloud/base/aws-iaas/config-template.yml
  private-cloud/base/aws-iaas/definition.yml
  private-cloud/base/aws-iaas/external_setup.yml
  private-cloud/base/aws-iaas/group_vars/all.yml
  private-cloud/base/aws-iaas/internal_setup.yml
  private-cloud/base/aws-iaas/inventory.yml
  private-cloud/base/aws-iaas/pre_setup.yml
  private-cloud/base/aws-iaas/pre_teardown.yml
  private-cloud/base/aws-iaas/roles/cluster_reqs/README.md
  private-cloud/base/aws-iaas/roles/cluster_reqs/defaults/main.yml
  private-cloud/base/aws-iaas/roles/cluster_reqs/meta/main.yml
  private-cloud/base/aws-iaas/roles/cluster_reqs/tasks/RedHat-post.yml
  private-cloud/base/aws-iaas/roles/cluster_reqs/tasks/Ubuntu-pre.yml
  private-cloud/base/aws-iaas/roles/cluster_reqs/tasks/default.yml
  private-cloud/base/aws-iaas/roles/cluster_reqs/tasks/main.yml
  private-cloud/base/aws-iaas/roles/cluster_reqs/tests/inventory
  private-cloud/base/aws-iaas/roles/cluster_reqs/tests/test.yml
  private-cloud/base/aws-iaas/roles/cluster_reqs/vars/RedHat.yml
  private-cloud/base/aws-iaas/roles/cluster_reqs/vars/Ubuntu.yml
  private-cloud/base/aws-iaas/roles/cluster_reqs/vars/default.yml
  private-cloud/base/aws-iaas/roles/cluster_reqs/vars/main.yml
  private-cloud/base/aws-iaas/summary.yml
  private-cloud/base/aws-iaas/templates/deployment.html.j2
  private-cloud/base/aws-iaas/templates/deployment.md.j2
  private-cloud/base/aws-iaas/templates/infra.tfvars.j2
  private-cloud/base/aws-iaas/tf_bastion/main.tf
  private-cloud/base/aws-iaas/tf_bastion/outputs.tf
  private-cloud/base/aws-iaas/tf_bastion/variables.tf
  private-cloud/base/aws-iaas/tf_hosts/main.tf
  private-cloud/base/aws-iaas/tf_hosts/outputs.tf
  private-cloud/base/aws-iaas/tf_hosts/variables.tf
  private-cloud/base/aws-iaas/tf_network/main.tf
  private-cloud/base/aws-iaas/tf_network/outputs.tf
  private-cloud/base/aws-iaas/tf_network/variables.tf
  private-cloud/base/aws-iaas/tf_proxied_cluster/main.tf
  private-cloud/base/aws-iaas/tf_proxied_cluster/outputs.tf
  private-cloud/base/aws-iaas/tf_proxied_cluster/variables.tf
  private-cloud/base/aws-iaas/validate_dns_lookups.yml
Labels: enhancement

#137 Fix ipa user search group & add base_teardown
  private-cloud/base/aws-iaas/base_teardown.yml
  private-cloud/base/aws-iaas/definition.yml
Labels: bug

#138 Add note about OSX stock Python issues
  README.md
Labels: documentation
